music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /music/album_id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /music/album_id/favorite
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title+ " - " +self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=200)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
#from django.http import HttpResponse
from .models import Album, Song
#from django.http import Http404

# # Create your views here.
# def index(request):
#     all_albums = Album.objects.all()
#     return render(request, 'music/index.html', {'all_albums' : all_albums})
#
# def detail(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {'album' : album})
#

from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album':album,
            'error_message': "You did not select a valid song",
        })
    else:
        if selected_song.is_favorite==False:
            selected_song.is_favorite = True
        else:
            selected_song.is_favorite = False
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add new Album{% endblock %}

{% block basic %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
          <div class="panel-body">

            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'music/form-template.html' %}
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-success">Submit</button>
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}MusicApp{% endblock %}</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'music:index' %}">MusicApp</a>
      </div>

      <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="{% url 'music:index' %}">
              <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
              Albums
            </a>
          </li>
          <li class="">
            <a href="#">
              <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
              Songs
            </a>
          </li>
        </ul>

        <form class="navbar-form navbar-left" role="search" method="get" action="#">
          <div class="form-group">
            <input type="text" class="form-control" name="q" value="">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <li class="">
            <a href="{% url 'music:album-add' %}">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
              Add Album
            </a>
          </li>
          <li class="">
            <a href="#">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
              Logout
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block basic %}
  {% endblock %}
</body>
<html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %}Album Detail{% endblock %}

{% block basic %}
  <img src="{{ album.album_logo }}"/>
  <h1>Title: {{ album.album_title }}</h1>
  <h3>Artist: {{ album.artist }}</h3>

  {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
  {% endif %}

  <form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
      <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
      <label for="song{{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_favorite %}
          <span style="color:red; font-size:20px">♥</span>
        {% endif %}
      </label>
      <br/>
    {% endfor %}
    <input type="submit" value="Favorite">
  </form>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class-"text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
  </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block basic %}
  {% if all_albums %}
    <ul>
      {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <h3>You don't have any albums</h3>
  {% endif %}
{% endblock %}